language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install: pip install https://github.com/meeron/pybinn/archive/v0.9.4-beta.zip

# command to run tests
script: py.test -v

branches:
  only: 
  - master
  - sqlite-based